/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Rainer Siebrandt
 */
public class viewGame extends javax.swing.JFrame {

    /**
     * Creates new form viewGame
     */
    public viewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlbP1Symbol = new javax.swing.JLabel();
        jlbP2Symbol = new javax.swing.JLabel();
        jedP1Symbol = new javax.swing.JTextField();
        jedP2Symbol = new javax.swing.JTextField();
        jlbPlayfield = new javax.swing.JLabel();
        jedPlayfield = new javax.swing.JTextField();
        jBtnRefresh = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe XTreme");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jlbP1Symbol.setText("Spieler 1 Symbol :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jlbP1Symbol, gridBagConstraints);

        jlbP2Symbol.setText("Spieler 2 Symbol :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(jlbP2Symbol, gridBagConstraints);

        jedP1Symbol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jedP1Symbol.setText("X");
        jedP1Symbol.setMaximumSize(new java.awt.Dimension(13, 20));
        jedP1Symbol.setMinimumSize(new java.awt.Dimension(13, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jedP1Symbol, gridBagConstraints);

        jedP2Symbol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jedP2Symbol.setText("Y");
        jedP2Symbol.setMaximumSize(new java.awt.Dimension(13, 20));
        jedP2Symbol.setMinimumSize(new java.awt.Dimension(13, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jedP2Symbol, gridBagConstraints);

        jlbPlayfield.setText("Spielfeld-Grösse :");
        jlbPlayfield.setMaximumSize(new java.awt.Dimension(120, 14));
        jlbPlayfield.setMinimumSize(new java.awt.Dimension(120, 14));
        jlbPlayfield.setPreferredSize(new java.awt.Dimension(120, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jlbPlayfield, gridBagConstraints);

        jedPlayfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jedPlayfield.setText("3");
        jedPlayfield.setMaximumSize(new java.awt.Dimension(40, 20));
        jedPlayfield.setMinimumSize(new java.awt.Dimension(40, 20));
        jedPlayfield.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jedPlayfield, gridBagConstraints);

        jBtnRefresh.setText("Aktualisieren");
        jBtnRefresh.setToolTipText("");
        jBtnRefresh.setMaximumSize(new java.awt.Dimension(160, 20));
        jBtnRefresh.setMinimumSize(new java.awt.Dimension(160, 20));
        jBtnRefresh.setName(""); // NOI18N
        jBtnRefresh.setPreferredSize(new java.awt.Dimension(160, 20));
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jBtnRefresh, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(filler3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        if(btnPanel != null)
            getContentPane().remove(btnPanel);
        
        int length = Integer.parseInt(jedPlayfield.getText());
        btnPanel = new JPanel();
        GridBagLayout gbl = new GridBagLayout();
        btnPanel.setLayout(gbl);
        
        Dimension dimBtn = new Dimension(50,50);
        
        for(int i = 0; i < length; i++){
            for(int j = 0; j < length; j++){
                JButton jBtn = new JButton();
                jBtn.setName("jBtn" + i + j);
                jBtn.setText(jBtn.getName());
                
                jBtn.setMinimumSize(dimBtn);
                jBtn.setMaximumSize(dimBtn);
                jBtn.setPreferredSize(dimBtn);
                
                var gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = i;
                gridBagConstraints.gridy = j;
                btnPanel.add(jBtn, gridBagConstraints);
            }
        }
        var gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        
        btnPanel.revalidate();
        
        getContentPane().add(btnPanel, gridBagConstraints);
        getContentPane().revalidate();
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewGame().setVisible(true);
            }
        });
    }
    private JPanel btnPanel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JTextField jedP1Symbol;
    private javax.swing.JTextField jedP2Symbol;
    private javax.swing.JTextField jedPlayfield;
    private javax.swing.JLabel jlbP1Symbol;
    private javax.swing.JLabel jlbP2Symbol;
    private javax.swing.JLabel jlbPlayfield;
    // End of variables declaration//GEN-END:variables
}
